# All environment variables are optional. If you don't set them, you will get a
# warning from docker-compose, however the app should use working defaults.

#https://github.com/laurent22/joplin/blob/dev/docker-compose.server.yml

version: '3'

services:
    db:
        image: postgres:13.1
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - "${DB_PORT}:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "${APP_PORT}:22300"
        restart: unless-stopped
        environment:
            - APP_PORT=${APP_PORT}
            - APP_BASE_URL=${APP_BASE_URL}
            - DB_CLIENT=${DB_CLIENT}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PORT=${DB_PORT}
            - POSTGRES_HOST=${POSTGRES_HOST}